### ISSUE TITLE
generated_cmake_targets for clang

### ISSUE THREAD

**Issue by defreez** [kythe/llvmbzlgen#10]
Thank you for releasing llvmbzlgen. By relying on the kythe bazel rules as an external dependency, I've been able to use it to generate bazel rules for building LLVM passes for the version of LLVM that I use. I run llvmbzlgen on the LLVMBuild.txt and CMakeLists.txt files at the root of the LLVM repo and, with a very small amount of modification, I can build LLVM passes. 

I'm having trouble getting it to work with clang. Specifically, I'm interested in building clang SA checkers with bazel.

What process do you use to create the kythe [generated_cmake_targets.bzl](https://github.com/kythe/kythe/blob/c4a354e835acef2b9eb14d026142f440b5871fd0/tools/build_rules/llvm/generated_cmake_targets.bzl#L469)?

I tried running it on the CMakeLists.txt from the clang subdirectory in [llvm-project](https://github.com/llvm/llvm-project), but the existing bazel rules, borrowed from kythe, seem to assume that clang lives under `llvm/tools`.

**Comment by shahms** [comment]
The biggest hurdle for Clang is that `llvmbzlgen` doesn't support loops, which are used to build the selected target architectures and selected tools.  It also expects the "old" llvm project layout, rather than that from GitHub.  As a result, I have a small shell script which symlinks clang under `llvm-project/llvm/tools` before running cmaketobzl:
```
#!/bin/bash
LLVM_ROOT=$HOME/src/llvm-project
LLVM_BUILD_FILE=generated_llvm_build_targets.bzl
CMAKE_FILE=generated_cmake_targets.bzl
ln -sf $(realpath $LLVM_ROOT/clang) $LLVM_ROOT/llvm/tools/
bazel run //tools/cmaketobzl -- \
  $LLVM_ROOT/llvm \
  $LLVM_ROOT/llvm/lib/Target/{X86,PowerPC,ARM,AArch64,Mips} \
  $LLVM_ROOT/llvm/tools/clang \
  > "$CMAKE_FILE"
buildifier "$CMAKE_FILE"
diff -u ~/src/kythe/tools/build_rules/llvm/$CMAKE_FILE $CMAKE_FILE | more

bazel run //tools/llvmbuildtobzl -- \
  $LLVM_ROOT/llvm \
  > "$LLVM_BUILD_FILE"
buildifier "$LLVM_BUILD_FILE"
diff -u ~/src/kythe/tools/build_rules/llvm/$LLVM_BUILD_FILE $LLVM_BUILD_FILE | more
```

As this is pretty specific to my directory layout, I haven't checked in anything equivalent yet, but it's on my TODO list.

**Comment by defreez-ucd** [comment]
Thank you for sharing your script! This clarifies the process.

**Comment by defreez** [comment]
Thank you for sharing your script! This clarifies the process.
